# See https://github.com/shufo/auto-assign-reviewer-by-files/blob/main/README.md for configuration format

"*":
  - team: flux

".github/**/*":
  - team: flux

"bin/*":
  - team: flux

"docs/**/*":
  - team: developer-advocacy

"packages/js/api/**/*":
  - team: solaris

"packages/js/e2e-utils/**/*":
  - team: solaris

"packages/js/e2e-environment/**/*":
  - team: solaris

"packages/js/api-core-tests/**/*":
  - team: solaris

"packages/js/e2e-core-tests/**/*":
  - team: solaris

"packages/js/admin-e2e-tests/**/*":
  - team: solaris

"packages/js/components/**/*":
  - team: woo-fse
  - team: ghidorah

"packages/js/csv-export/**/*":
  - team: woo-fse

"packages/js/currency/**/*":
  - team: fractal

"packages/js/customer-effort-score/**/*":
  - team: woo-fse
  - team: ghidorah

"packages/js/data/**/*":
  - team: woo-fse
  - team: ghidorah

"packages/js/date/**/*":
  - team: woo-fse

"packages/js/dependency-extraction-webpack-plugin/**/*":
  - team: flux

"packages/js/eslint-plugin/**/*":
  - team: flux

"packages/js/experimental/**/*":
  - team: woo-fse

"packages/js/explat/**/*":
  - team: woo-fse
  - team: ghidorah

"packages/js/navigation/**/*":
  - team: woo-fse

"packages/js/number/**/*":
  - team: woo-fse

"packages/js/onboarding/**/*":
  - team: ghidorah

"packages/js/product-editor/**/*":
  - team: woo-fse

"packages/js/tracks/**/*":
  - team: woo-fse
  - team: ghidorah

"plugins/woocommerce/**/*":
  - team: proton

"plugins/woocommerce/templates/**/*":
  - team: rubik
  - team: woo-fse

"plugins/woocommerce/templates/emails/**/*":
  - team: proton

"plugins/woocommerce/src/Admin/**/*":
  - team: woo-fse
  - team: ghidorah

"plugins/woocommerce/src/Blocks/**/*":
  - team: rubik
  - team: woo-fse

"plugins/woocommerce/src/Internal/Admin/**/*":
  - team: woo-fse
  - team: ghidorah

"plugins/woocommerce/src/StoreApi/**/*":
  - team: rubik
  - team: woo-fse

"plugins/woocommerce/client/admin/**/*":
  - team: woo-fse
  - team: ghidorah

"plugins/woocommerce-blocks/**/*":
  - team: rubik
  - team: woo-fse

"plugins/woocommerce-beta-tester/**/*":
  - team: ghidorah

"tools/**/*":
  - team: flux

'**/composer.json':
  - team: flux

'**/package.json':
  - team: flux
