name: Send PRs that require further testing to Slack
on:
  pull_request_target:
    types: [labeled]

permissions: {}

jobs:
  send-pr-to-slack-for-further-testing:
    if: "${{ github.event.label.name == 'needs: analysis' && (github.event.pull_request.state == 'open' || github.event.pull_request.merged) }}"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/actions/pr-scrub-notify-slack
          ref: trunk
      - name: 'Trigger PR scrub'
        uses: ./.github/actions/pr-scrub-notify-slack
        with:
          TEST_ASSISTANCE_BOT_TOKEN: ${{ secrets.TEST_ASSISTANCE_BOT_TOKEN }}
          WOO_PR_TESTING_ANALYSIS_SLACK_CHANNEL: ${{ secrets.WOO_PR_TESTING_ANALYSIS_SLACK_CHANNEL }}
          WOO_PR_TESTING_ANALYSIS_TEAM_ID: ${{ secrets.WOO_PR_TESTING_ANALYSIS_TEAM_ID }}

